### ISSUE TITLE
The program crashed with a "Name or service not known" error, and only downloaded 20 images

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/4scanner#10]
I ran the program, and it said that it found 13 threads, and would check again in 10 minutes. But less than 10 minutes later, it gave this error:

`06/Apr/2016-18:24 Searching threads...`
`13 Threads download are active!`
`Searching again in 10 minutes!`
`Exception in thread Thread-5:`
`Traceback (most recent call last):`
  `File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open`
    `h.request(req.get_method(), req.selector, req.data, headers)`
  `File "/usr/lib/python3.4/http/client.py", line 1088, in request`
    `self._send_request(method, url, body, headers)`
  `File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request`
    `self.endheaders(body)`
  `File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders`
    `self._send_output(message_body)`
  `File "/usr/lib/python3.4/http/client.py", line 922, in _send_output`
    `self.send(msg)`
  `File "/usr/lib/python3.4/http/client.py", line 857, in send`
    `self.connect()`
  `File "/usr/lib/python3.4/http/client.py", line 834, in connect`
    `self.timeout, self.source_address)`
  `File "/usr/lib/python3.4/socket.py", line 494, in create_connection`
    `for res in getaddrinfo(host, port, 0, SOCK_STREAM):`
  `File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo`
    `for res in _socket.getaddrinfo(host, port, family, type, proto, flags):`
`socket.gaierror: [Errno -2] Name or service not known`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`
  `File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner`
    `self.run()`
  `File "/usr/lib/python3.4/threading.py", line 868, in run`
    `self._target(*self._args, **self._kwargs)`
  `File "/usr/local/lib/python3.4/dist-packages/scanner/download.py", line 55, in download_thread`
    `urllib.request.urlretrieve('http:' + link, directory + img)`
  `File "/usr/lib/python3.4/urllib/request.py", line 186, in urlretrieve`
    `with contextlib.closing(urlopen(url, data)) as fp:`
  `File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen`
    `return opener.open(url, data, timeout)`
  `File "/usr/lib/python3.4/urllib/request.py", line 463, in open`
    `response = self._open(req, data)`
  `File "/usr/lib/python3.4/urllib/request.py", line 481, in _open`
    `'_open', req)`
  `File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain`
    `result = func(*args)`
  `File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open`
    `return self.do_open(http.client.HTTPConnection, req)`
  `File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open`
    `raise URLError(err)`
`urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>`

Now, the program didn't close, but:

1. It only downloaded about 20 images, when there are hundreds on 4chan.
2. Some of the images are broken/corruped.

What could be happening here?

**Comment by Lacsap-** [comment]
It seems that for some unknown reason the script is trying to download a 404'd image causing the thread where the picture was found to stop downloading, all other threads are still downloading fine though.

I'll try to make a fix for this ASAP.

In the meantime the rest of your threads will continue downloading and 4scanner will continue looking for new threads every 10 minute

Thanks for testing the script by the way!

**Comment by Lacsap-** [comment]
I made a quick fix, there is now an exception checking on every image downloaded. So if an image fail to download the rest of the thread should still download without problem.

Just update 4scanner with pip3 to get the fix!

**Comment by Rich700000000000** [comment]
Got it.

**Comment by Lacsap-** [comment]
Good! 
I'll close this issue for now if all is working. If you got any other problems just open another issue.

**Comment by Rich700000000000** [comment]
Hey, it crashed again. It gave the same error, except this time, the program actually ended, and went back to the terminal.

Is there some way I can give you more information?

**Comment by Lacsap-** [comment]
what does the "pip3 freeze" command gives you? it should say something like 4scanner==1.0.5

Theres nothing different in the error message? is the error still on this line like in the first error?
```
File "/usr/local/lib/python3.4/dist-packages/scanner/download.py", line 55, in download_thread
urllib.request.urlretrieve('http:' + link, directory + img)
```

**Comment by Rich700000000000** [comment]
Yeah, it says `4scanner==1.0.5`. 

The full error message is here: http://pastebin.com/pNT4i4BA

**Comment by Lacsap-** [comment]
Ok I think I know whats causing your problem, I don't have time to fix it right now but I'll try to fix it tomorrow morning. I can't replicate it on my machine though for some reason.

**Comment by Rich700000000000** [comment]
Got it.

**Comment by Lacsap-** [comment]
I never managed to reproduce the issue but there is now a check when trying to get all the thread of a board. (this is where the crash was happening for you) If 4scanner can't get the thread catalog from 4chan it will print something like: Error while opening [board] catalog page. Retrying during next scan.

Nothing will be downloaded for this board but 4scanner will try searching it again after 10 minutes.

New 4scanner version is 1.0.7

**Comment by Lacsap-** [comment]
Could you give me an update on this issue when you have some time so I can close the issue or continue working on a fix?

**Comment by Rich700000000000** [comment]
Sorry, it seems to be working fine now. If I get any more problems I'll let you know.

**Comment by Lacsap-** [comment]
All good!
