### ISSUE TITLE
[Request] Longterm continuous running, for server/VPS setups.

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/4scanner#13]
So, I think that there should be a function to set this for long-term server use, to gather images from multiple chans (4chan, 8chan, 420chan, etc.) over a period of months. 

Problems to solve:

* Making an extractor for each site.
* Dedicated duplicate detection.
* Making the program automatically restart upon crashes/reboots/updates (very important.) 
* Sending you a message when your quota/limit/storage is up.
* Building a image/thread selector far, far more detailed.
* Automatic FTP uploads?
* Encryption?

What do you think?

**Comment by Lacsap-** [comment]
I think some of it could be useful:
- Making an extractor for each site.

I already plan to add support for some more imageboards it's gonna be configurable in the .json file.
(I don't know when I'll have time to code the feature though)
- Dedicated duplicate detection.

That would be nice, until I get around to coding something you can run fdupes in a cronjob or something.
- Making the program automatically restart upon crashes/reboots/updates (very important.)

Just make a systemd service with the script, this way it's gonna be restarted on crash. I'll try making an example systemd service file soon

- Sending you a message when your quota/limit/storage is up.

That's a good idea, I might look into it.
- Building a image/thread selector far, far more detailed.

What do you have in mind?
- Automatic FTP uploads?

It could be done but I have no plan to do it.
- Encryption?

I have no plan to make that but I don't think it would be that hard to code.


I'll try to get working on some of those features soon but if you know some python you can try coding them and making a pull request!

Thanks for all the suggestions.

**Comment by Rich700000000000** [comment]
Cool.

What I mean by point five was more if/than options, like:

_Ok, if the thread has more than 20 images, download ALL images ABOVE 1000x1000 resolution but UNDER 2000x2000 resolution that DONT have "IMG__" _in the filename_.

Or something like that.

**Comment by Lacsap-** [comment]
This would be a lot of work but it could be a great feature. I'll make an issue for each things we talked about here so we can discuss about them individually.

**Comment by Lacsap-** [comment]
But I don't understand the purpose of the ftp upload, if you have an always up host with a FTP server waiting to download images, why don't you just run 4scanner on it?

And how would your encryption work? encrypt every image downloaded with pgp?

I also won't be making an issue for restarting on crash since you can just make 4scanner a systemd/upstart service.

**Comment by Rich700000000000** [comment]
Sorry, I was just brainstorming.

**Comment by Lacsap-** [comment]
No problem, new ideas are always good! I just wanted to know if you think there is any use for the FTP.

**Comment by Lacsap-** [comment]
I'll close this issue since I made a separate issue for most of the things in here. If theres anything I forgot from here that you want feel free to create issues for them.
