### ISSUE TITLE
[Question] How to use the test folder?

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/4scanner#17]
Hey, I made a few small changes to my fork. How do I use the "test" folder? I want to make sure everything's working right before I submit a pull request.

**Comment by Lacsap-** [comment]
You can either turn on Travis CI on your fork of 4scanner (it's somewhere in your fork settings) or just submit a pull request and travis will run from the main repo and tells you if a test failed. To be honest though my travis tests are still kind of bad. (they cover maybe 50% of the code max) I need to fix them soon.

**Comment by Rich700000000000** [comment]
>Travis CI 

I.. have never heard of this. I'm sorry. How does it work?

**Comment by Lacsap-** [comment]
Oh sorry, Travis is a continuous integration tool. It is integrated with github and can be used to automatically run tests. (for 4scanner those test are in ```test/test.py```) After Travis run the tests it will report either a success or a failure, failure means that you broke something with your code changes.
If you check 4scanner README.md you can see if the last test Travis ran failed or succeded  ([![Build Status](https://travis-ci.org/Lacsap-/4scanner.svg?branch=master)](https://travis-ci.org/Lacsap-/4scanner))

Travis will also automatically run on pull request to check if the new code breaks anything.

For info here is the 4scanner travis page : https://travis-ci.org/Lacsap-/4scanner

**Comment by Rich700000000000** [comment]
So, I just submit a pull request and it will automatically check? Cool.

**Comment by Lacsap-** [comment]
Exactly, nothing broke because of your pull request so the test succeeded:
http://i.imgur.com/mJuocEP.png
