### ISSUE TITLE
[Question] How do I synchronize my fork with the main project?

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/4scanner#23]
I apologize, but I'm still new to github. It says that my branch is six commits behind yours. How do I pull your updates into my repo? 

When I click on compare, it says that there isn't anything.

**Comment by Lacsap-** [comment]
- git checkout master
- git pull

**Comment by Rich700000000000** [comment]
I'm so sorry, but I'm still really lost: I usually use the web interface. Where would you recommend as a starting point to the terminal commands?

**Comment by Lacsap-** [comment]
Are you using Windows? If you are I have no idea, I think you can use the gitbash application to use git commands on Windows but I never tried it. If you are on linux/mac you can just install git and open a terminal to enter the commands. (your terminal needs to be in the directory where you cloned 4scanner)

**Comment by Rich700000000000** [comment]
OK: I just tried to update my repo. I think it worked, but if I accidentally messed up something, let me know, ok?

**Comment by Lacsap-** [comment]
Sure, and when you make a pull request I have to accept and merge it myself so there is no problem.
