### ISSUE TITLE
[Question] How does the "chan_info" selector work, exactly?

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/4scanner#24]
It seems like a really good idea, but I still have some questions:

1. Where does it get the actual website from from? The way I see it, you would need a slicer to extract the actual chan from the url:

        url = "https://www.4chan.org/"
        dis,chan1 = url.split("www.")
        chan,dis2 = chan1.split(".org")
        if chan == "4chan":
           do x
        if chan == "8chan":
           do y
but I don't see that anywhere.

2.  Does it only work on chans with a json API? Because if so, than the chan_info selector would be very  limited it use.  But if not, than I could easily add in the base for every chan. (7chan, 8chan, 420chan, etc.)

**Comment by Lacsap-** [comment]
1. It get the imageboard from your json config. If you check the README.md you can see this example:
```
{"searches":[
    {
      "imageboard":"IMAGEBOARD",
      "folder_name":"YOUR_FOLDER_NAME",
      "board": "BOARD_LETTER",
      "keywords": ["KEYWORD1", "KEYWORD2"]
    },

    {
      "imageboard":"4chan",
      "folder_name":"vidya",
      "board": "v",
      "keywords": ["tf2", "splatoon", "world of tank"]
    }
]}
```

4scanner get the imageboard from ```"imageboard":"IMAGEBOARD"``` and default to 4chan if ```"imageboard":``` is missing from your search.

2. Yes, it only work on imageboards with a JSON API. (which is most imageboards)

**Comment by Lacsap-** [comment]
This is the part of the code that handle which imageboard to use (scanner/scanner.py): 

```
if 'imageboard' in search:
                chan = search["imageboard"]
                if not chan_info.get_chan_info(chan):
                    print("{0} is not supported.".format(chan))
                    exit(1)
            else:
                # default
                chan = "4chan"
```

**Comment by Rich700000000000** [comment]
Ok. How would I check if the imageboard I want to scrape has a JSON API or not?

**Comment by Lacsap-** [comment]
Try switching .html for .json on some pages.

for example:
```https://8ch.net/n/catalog.html``` is the normal catalog
```https://8ch.net/n/catalog.json``` is the json version of the catalog

If you get a 404 then most likely they don't have a JSON api (or it may be a bit different from other imageboards, try searching if there is a page about their API somewhere)

unrelated to the question: I always get a 403 denied when I try to access 8ch json API from 4scanner for some reason.

**Comment by Rich700000000000** [comment]
Have you tried using a user-agent? I had a similar problem a while back, and adding a user agent helped me fix it.

**Comment by Lacsap-** [comment]
Not yet, I'll try soon. But it would be weird that they have an api that can't be accessed by a script.

**Comment by Lacsap-** [comment]
I'll close this since the question has been answered.
