### ISSUE TITLE
Server usage; requires a quota

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/4scanner#26]
I recently installed 4scanner on a DigitalOcean droplet. There were no problems, it ran without crashing, however it wouldn't start without a quota. 

Was that supposed to be mandatory?

**Comment by Lacsap-** [comment]
woops, nope it shouldn't be mandatory. I'll try to fix it soon, in the meantime you can call it with -q 99999G to bypass the problem. Sorry for that!

**Comment by Lacsap-** [comment]
Should be fixed in #27 !
