### ISSUE TITLE
Paypal/Donations?

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/4scanner#30]
This project seems to have a good deal of work put into it, and I haven't had the time to submit code. I don't wan't to take advantage of your ongoing efforts without you getting anything in return.

**Comment by Lacsap-** [comment]
Don't worry you are not taking advantage at all. I made 4scanner open source so people could use it!     :)  The issues you opened also helped make 4scanner more robust. But donation is very appreciated for sure if you feel like my work is worth it! If you decide to donate my paypal account is: pascalboardman@gmail.com

**Comment by Rich700000000000** [comment]
Got it.
