### ISSUE TITLE
How to update fork?

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/4scanner#35]
Hey, how do I update my fork? I'm 32 commits behind the main.

**Comment by Lacsap-** [comment]
You can do a:
  •  git checkout master
  •  git pull

Or I guess you could delete your fork and fork 4scanner again.

**Comment by Lacsap-** [comment]
Did it work for you? Can I close the issue?

**Comment by Rich700000000000** [comment]
Sure.
