### ISSUE TITLE
Crashes at two hours and 4 minutes, possibly my system?

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/4scanner#38]
I started it on my desktop at 2:32. It ran fine for two hours and downloaded 1,483 images in that time. Until, at 4:36, it crashed with a very, _very_ long error message:

```
28/Jul/2016-04:36 Searching threads...
Error while opening HC catalog page. Retrying during next scan.
17 threads currently downloading.
Searching again in 5 minutes!
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
```

It goes on for over 400 more lines.

One thing I'm worried about is that there may be something wrong with my system, I keep getting errors that aren't bothering you. Just a few days ago, this desktop gave me another error on a different script, that ran too long. Am I doing something wrong?

**Comment by Lacsap-** [comment]
Maybe your internet connection is unstable? From the error message it looks like your internet connection dropped.

If you still have it, could you paste the whole error message?

**Comment by Rich700000000000** [comment]
Here you go: https://gist.github.com/Rich700000000000/91bc6cf1f42378637287370506ca0c9a

**Comment by Lacsap-** [comment]
From what I can see it really looks like an internet connection issue. Maybe you can try running 4scanner with your JSON file on a VPS to see if it still crash. If it doesn't then your internet connection is most likely the problem.

**Comment by Rich700000000000** [comment]
I've used a VPS before, but how would I save the error message?

**Comment by Rich700000000000** [comment]
It would be running headless, in the background.

**Comment by Lacsap-** [comment]
You can use ` screen ` to make a terminal you can reattach to and get the logs, or just redirect output to a file ` > `

**Comment by Rich700000000000** [comment]
Got it. I'll work on that, and get back to you as soon as I can.

**Comment by Lacsap-** [comment]
Any update on this? I'll close the issue for now. If you still need help don't hesitate to reopen it.
