### ISSUE TITLE
[Bug] Returns "delimiter error"

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/4scanner#9]
I installed 4scanner with pip, and then made my json. 

However, when I tried to run it, I got an error: 

`dave@dave-HP-EliteBook-8560w:~/Code/Active - Long$ 4scanner file.json`
`05/Apr/2016-14:31 Searching threads...`
`Traceback (most recent call last):`
  `File "/usr/local/bin/4scanner", line 38, in <module>`
    `main()`
  `File "/usr/local/bin/4scanner", line 33, in main`
    `scanner.scan(args.keywords_file, output, log_file)`
  `File "/usr/local/lib/python3.4/dist-packages/scanner/scanner.py", line 63, in scan`
    `json_file = json.load(open(keywords_file))`
  `File "/usr/lib/python3.4/json/__init__.py", line 268, in load`
    `parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)`
  `File "/usr/lib/python3.4/json/__init__.py", line 318, in loads`
    `return _default_decoder.decode(s)`
  `File "/usr/lib/python3.4/json/decoder.py", line 343, in decode`
    `obj, end = self.raw_decode(s, idx=_w(s, 0).end())`
  `File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode`
    `obj, end = self.scan_once(s, idx)`
`ValueError: Expecting ',' delimiter: line 8 column 5 (char 152)`

What could be causing this?

**Comment by Lacsap-** [comment]
Could you post your json file here so I can check whats wrong with it?

**Comment by Rich700000000000** [comment]
`{"searches":[`
    `{`
      `"folder_name":"Asian",`
      `"board": "hm",`
      `"keywords": ["asian", "chinese", "japanese", "korean"]`
    `}`

    {
      "folder_name":"HR - Minaj",
      "board": "hr",
      "keywords": ["niki", "minaj"]
    }

    {
      "folder_name":"Rails",
      "board": "n",
      "keywords": ["trains", "rails", "tracks", "amtrack", "rail lines"]
    }
`]}`

Sorry the formatting is weird.

**Comment by Lacsap-** [comment]
I'm at work right now so I can't test, but try it like this it should work:

```
{"searches":[
    {
    "folder_name":"Asian",
    "board": "hm",
    "keywords": ["asian", "chinese", "japanese", "korean"]
    },

    {
      "folder_name":"HR - Minaj",
      "board": "hr",
      "keywords": ["niki", "minaj"]
    },

    {
      "folder_name":"Rails",
      "board": "n",
      "keywords": ["trains", "rails", "tracks", "amtrack", "rail lines"]
    }
]}
```


I added a some missings ','.

**Comment by Rich700000000000** [comment]
It's working now, thanks!
